[project]
name = 'Transparent-Humanitarian-Aid-Distribution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.distribution-verification]
path = 'contracts/distribution-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.receipient-verification]
path = 'contracts/receipient-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-tracking]
path = 'contracts/resource-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
